#!/usr/bin/env python

from twisted.python import log
from twisted.internet import reactor
import sys

from doctoreval import start

def main(args=None):
    log.startLogging(sys.stdout)
    reactor.callLater(0, start)
    reactor.run()

if __name__ == '__main__':
    main()