#!/usr/bin/env python

from twisted.python import log
from twisted.internet import reactor
import sys

from doctoreval import start

def main(args=None):
    log.startLogging(sys.stdout)
    port = int(args[args.index('-p') + 1]) if '-p' in args else 8123
    reactor.callLater(0, start, port=port)
    reactor.run()

if __name__ == '__main__':
    main(sys.argv)